export const ALL_COUNTRIES = [
  'Afganistan', 'Almanya', 'Amerika Birleşik Devletleri', 'Angola', 'Arjantin',
  'Arnavutluk', 'Avustralya', 'Avusturya', 'Azerbaycan',
  'Bahreyn', 'Bangladeş', 'Belçika', 'Beyaz Rusya', 'Bolivya', 'Bosna Hersek',
  'Botsvana', 'Brezilya', 'Brunei', 'Bulgaristan', 'Burkina Faso', 'Burundi',
  'Cezayir', 'Cibuti', 'Çad', 'Çek Cumhuriyeti', 'Çin',
  'Danimarka', 'Demokratik Kongo Cumhuriyeti', 'Dominik Cumhuriyeti',
  'Ekvator', 'Ekvator Ginesi', 'El Salvador', 'Endonezya', 'Eritre', 'Ermenistan', 'Estonya', 'Etiyopya',
  'Fas', 'Fiji', 'Fildişi Sahili', 'Filipinler', 'Finlandiya', 'Fransa',
  'Gabon', 'Gambiya', 'Gana', 'Güney Afrika', 'Güney Kore', 'Güney Sudan', 'Gürcistan',
  'Guatemala', 'Gine', 'Gine-Bissau',
  'Haiti', 'Hırvatistan', 'Hindistan', 'Hollanda', 'Honduras', 'Irak', 'İran', 'İrlanda', 'İspanya', 'İsrail', 'İsveç', 'İsviçre', 'İtalya', 'İzlanda',
  'Jamaika', 'Japonya',
  'Kamboçya', 'Kamerun', 'Kanada', 'Kazakistan', 'Kenya', 'Kıbrıs', 'Kırgızistan', 'Kolombiya', 'Komor Adaları', 'Kongo', 'Kosova', 'Kosta Rika', 'Küba', 'Kuveyt',
  'Laos', 'Lesotho', 'Letonya', 'Liberya', 'Libya', 'Lihtenştayn', 'Litvanya', 'Lübnan', 'Lüksemburg',
  'Macaristan', 'Madagaskar', 'Malavi', 'Maldivler', 'Malezya', 'Mali', 'Malta', 'Meksika', 'Mısır', 'Moğolistan', 'Moldova', 'Monako', 'Mozambik',
  'Myanmar',
  'Namibya', 'Nepal', 'Nijer', 'Nijerya', 'Nikaragua', 'Norveç',
  'Orta Afrika Cumhuriyeti', 'Özbekistan',
  'Pakistan', 'Panama', 'Papua Yeni Gine', 'Paraguay', 'Peru', 'Polonya', 'Portekiz',
  'Romanya', 'Ruanda', 'Rusya',
  'Senegal', 'Sierra Leone', 'Singapur', 'Sırbistan', 'Slovakya', 'Slovenya', 'Somali', 'Sri Lanka', 'Sudan', 'Suriye',
  'Suudi Arabistan',
  'Tacikistan', 'Tanzania', 'Tayland', 'Togo', 'Trinidad ve Tobago', 'Tunus', 'Türkiye', 'Türkmenistan',
  'Uganda', 'Ukrayna', 'Umman', 'Uruguay',
  'Venezuela', 'Vietnam',
  'Yemen', 'Yeni Zelanda', 'Yunanistan',
  'Zambiya', 'Zimbabve',
]
